# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PW: ${{ secrets.DB_PW }}
      DB_USER: ${{ secrets.DB_USER }}
    strategy:
      matrix:
        R: ["3.5.3", "3.6.1"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          r-version: ${{ matrix.R }}
      - name: run query
        run: |
          Rscript -e 'print("이거 안되는건가?")'
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
